"""empty message

Revision ID: 0dac6194485f
Revises: e06add2e2e35
Create Date: 2025-01-26 13:49:39.243592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dac6194485f'
down_revision = 'e06add2e2e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'reports', ['report_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('report_id')

    # ### end Alembic commands ###
