"""empty message

Revision ID: 388768830e9c
Revises: 7f10bfd100bc
Create Date: 2025-01-30 14:37:38.370672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388768830e9c'
down_revision = '7f10bfd100bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('new_quantity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('stock_movement')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_movement', sa.INTEGER(), autoincrement=False, nullable=False))

    op.drop_table('stock_movements')
    # ### end Alembic commands ###
