"""Scaled down to the initial model without login handlings

Revision ID: 8d8511b013ea
Revises: bc44765e85e5
Create Date: 2025-02-05 14:07:08.451062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8511b013ea'
down_revision = 'bc44765e85e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_api_key_key', type_='unique')
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.VARCHAR(), server_default=sa.text("'default_api_key_value'::character varying"), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('users_api_key_key', ['api_key'])

    # ### end Alembic commands ###
