"""Added product id back into Stock Movement model

Revision ID: 99510dd6a742
Revises: cc05ea6fd744
Create Date: 2025-02-06 19:54:15.880799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99510dd6a742'
down_revision = 'cc05ea6fd744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
